### ISSUE TITLE
Complete Chronic Homelessness Logic. 

### ISSUE THREAD

**Issue by timbender-ncceh** [timbender-ncceh/PIT_HIC#17]
https://github.com/timbender-ncceh/PIT_HIC/blob/2621d733187d6b0530746307e87f4dc62232c5d9/pit_chronically_homeless_logic.R#L7

## Problem: ##
Need to incorporate complicated chronic homelessness logic into PIT unsheltered report.  Rather than coding it, there is a BO report that we can run ourselves and then join into the data.  

## To-Do: ##
- [x] Document How to download report from BO by shadowing brian, etc.  (see notes in comment below). 
- [x] Document how to join and filter BO report down to what you need (see notes in comment below)
- [x] Code logic
- [ ] Compare total rate of Chronic Homelessness with andrea's initial check (join outside of R) of 11.5% Chronic
- [x]  Send draft output to andrea with CH status column (near household type column)

## Important Info ##
- Report Name (BO):
- Report Filename (xlsx): 
-

**Comment by timbender-ncceh** [comment]
Notes on the BO shadowing of Brian: 

SHADOW BRIAN IN HMIS
GO TO BRIAN'S BO INBOX


JOIN 
FORMAT INTERMITTENT HEADERS
KEEP MOST RECENT ENTRY DATE BY CLIENT (HMIS ID)

**Comment by andreaNCCEH** [comment]
Other Important Info: the report is A003 Chronic Homeless Check and the three columns needed are Client ID, Start Date, and Chronic Status in order to sort and join appropriately.

**Comment by andreaNCCEH** [comment]
- [ ] Compare total rate of Chronic Homelessness with andrea's initial check (join outside of R) of 11.5% Chronic
- [ ] Send draft output to andrea with CH status column (near household type column)

**Comment by timbender-ncceh** [comment]
> * [ ]  ~~Compare total rate of Chronic Homelessness with andrea's initial check (join outside of R) of 11.5% Chronic~~
> * [ ]  ~~Send draft output to andrea with CH status column (near household type column)~~

I have added these to the main issue body (top) so will check them off in your comment above @andreaNCCEH

**Comment by andreaNCCEH** [comment]
It says you compared the rate of chronically homeless clients. What was that rate? 

- [ ] Can you add the column HouseholdID to the Andrea's Output? This will help me see who's grouped together. If it could be near householdType_def or HoH_PersonalID that would help me scroll through data.

**Comment by timbender-ncceh** [comment]
> It says you compared the rate of chronically homeless clients. What was that rate?
> 
> * Can you add the column HouseholdID to the Andrea's Output? This will help me see who's grouped together. If it could be near householdType_def or HoH_PersonalID that would help me scroll through data.

To summarise, you are asking the following @andreaNCCEH :

- [ ] Add HouseholdID to Andrea'sOutput.xlsx near householdType_def or HoHPersonalID, 
- [ ] What was the overall rate of chronically homeless **_clients_**?
